/**
 * Hand-written types matching supabase/migrations/0001_init.sql and
 * 0002_domain_schema.sql.
 *
 * Once your Supabase project is linked, regenerate the real (guaranteed
 * accurate) types and replace this file entirely:
 *
 *   npx supabase gen types typescript --project-id <your-project-ref> > src/types/database.types.ts
 *
 * Until then, keep this file in sync by hand whenever a migration changes
 * the schema — the Supabase client is generic over this type, so a
 * mismatch won't fail the build, it'll just type-check against the wrong
 * shape.
 *
 * Each table below follows the shape the Supabase CLI generates: `Row` is
 * what a select returns, `Insert` is what you may pass to `.insert()`
 * (columns with a default or that are nullable are optional), `Update` is
 * everything optional (what `.update()` accepts). Columns generated by
 * Postgres (`tyre_details.size_label`) are omitted from Insert/Update —
 * the database rejects an explicit value for those.
 */

// 'staff' is a legacy fallback value — new accounts default to
// 'mechanic' as of migration 0004. Kept on the enum for compatibility;
// don't default new UI to it.
export type StaffRole = "admin" | "manager" | "mechanic" | "staff"
export type StockItemType = "part" | "tyre"
export type TyreSeason = "summer" | "winter" | "all_season"
export type TyreTier = "budget" | "mid_range" | "premium"
export type StockMovementType =
  | "initial"
  | "goods_in"
  | "used"
  | "return_to_supplier"
  | "adjustment"
export type PurchaseOrderStatus =
  | "draft"
  | "ordered"
  | "partially_received"
  | "received"
  | "cancelled"
export type SupplierReturnStatus = "draft" | "sent" | "credited"

// ---------------------------------------------------------------------
// profiles (0001_init.sql)
// ---------------------------------------------------------------------

export type ProfileRow = {
  id: string
  full_name: string
  role: StaffRole
  created_at: string
  updated_at: string
}
export type ProfileInsert = {
  id: string
  full_name: string
  role?: StaffRole
  created_at?: string
  updated_at?: string
}
export type ProfileUpdate = Partial<ProfileInsert>

// ---------------------------------------------------------------------
// suppliers
// ---------------------------------------------------------------------

export type SupplierRow = {
  id: string
  name: string
  contact_name: string | null
  phone: string | null
  email: string | null
  notes: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}
export type SupplierInsert = {
  id?: string
  name: string
  contact_name?: string | null
  phone?: string | null
  email?: string | null
  notes?: string | null
  is_active?: boolean
  created_at?: string
  updated_at?: string
}
export type SupplierUpdate = Partial<SupplierInsert>

// ---------------------------------------------------------------------
// stock_items
// ---------------------------------------------------------------------

export type StockItemRow = {
  id: string
  item_type: StockItemType
  id_number: string
  barcode: string | null
  name: string
  supplier_id: string | null
  cost_price: number
  selling_price: number
  is_non_returnable: boolean
  is_consignment: boolean
  vehicle_note: string | null
  quantity_on_hand: number
  ideal_stock_level: number
  location: string | null
  notes: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}
export type StockItemInsert = {
  id?: string
  item_type: StockItemType
  id_number: string
  barcode?: string | null
  name: string
  supplier_id?: string | null
  cost_price?: number
  selling_price?: number
  is_non_returnable?: boolean
  is_consignment?: boolean
  vehicle_note?: string | null
  quantity_on_hand?: number
  ideal_stock_level?: number
  location?: string | null
  notes?: string | null
  is_active?: boolean
  created_at?: string
  updated_at?: string
}
export type StockItemUpdate = Partial<StockItemInsert>

// ---------------------------------------------------------------------
// part_details
// ---------------------------------------------------------------------

export type PartDetailsRow = {
  stock_item_id: string
  vehicle_make: string | null
  vehicle_model: string | null
  manufacturer_part_number: string | null
  oem_part_number: string | null
}
export type PartDetailsInsert = {
  stock_item_id: string
  vehicle_make?: string | null
  vehicle_model?: string | null
  manufacturer_part_number?: string | null
  oem_part_number?: string | null
}
export type PartDetailsUpdate = Partial<PartDetailsInsert>

// ---------------------------------------------------------------------
// tyre_details
// ---------------------------------------------------------------------

export type TyreDetailsRow = {
  stock_item_id: string
  width: number
  profile: number
  rim_diameter: number
  size_label: string // generated column — read-only
  load_index: string | null
  speed_rating: string | null
  is_xl: boolean
  is_commercial: boolean
  season: TyreSeason
  tier: TyreTier
  brand: string | null
  pattern: string | null
}
export type TyreDetailsInsert = {
  stock_item_id: string
  width: number
  profile: number
  rim_diameter: number
  load_index?: string | null
  speed_rating?: string | null
  is_xl?: boolean
  is_commercial?: boolean
  season?: TyreSeason
  tier?: TyreTier
  brand?: string | null
  pattern?: string | null
}
export type TyreDetailsUpdate = Partial<TyreDetailsInsert>

// ---------------------------------------------------------------------
// stock_movements (append-only ledger)
// ---------------------------------------------------------------------

export type StockMovementRow = {
  id: string
  stock_item_id: string
  movement_type: StockMovementType
  quantity: number
  job_number: string | null
  purchase_order_id: string | null
  supplier_return_id: string | null
  performed_by: string | null
  notes: string | null
  created_at: string
}
export type StockMovementInsert = {
  id?: string
  stock_item_id: string
  movement_type: StockMovementType
  quantity: number
  job_number?: string | null
  purchase_order_id?: string | null
  supplier_return_id?: string | null
  performed_by?: string | null
  notes?: string | null
  created_at?: string
}
// No update type exported: the ledger is append-only (see RLS policy in
// 0002_domain_schema.sql) — there is intentionally no UPDATE policy.

// ---------------------------------------------------------------------
// purchase_orders / purchase_order_lines
// ---------------------------------------------------------------------

export type PurchaseOrderRow = {
  id: string
  supplier_id: string
  status: PurchaseOrderStatus
  ordered_at: string | null
  expected_at: string | null
  created_by: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type PurchaseOrderInsert = {
  id?: string
  supplier_id: string
  status?: PurchaseOrderStatus
  ordered_at?: string | null
  expected_at?: string | null
  created_by?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type PurchaseOrderUpdate = Partial<PurchaseOrderInsert>

export type PurchaseOrderLineRow = {
  id: string
  purchase_order_id: string
  stock_item_id: string
  quantity_ordered: number
  quantity_received: number
  unit_cost: number
  created_at: string
  updated_at: string
}
export type PurchaseOrderLineInsert = {
  id?: string
  purchase_order_id: string
  stock_item_id: string
  quantity_ordered: number
  quantity_received?: number
  unit_cost: number
  created_at?: string
  updated_at?: string
}
export type PurchaseOrderLineUpdate = Partial<PurchaseOrderLineInsert>

// ---------------------------------------------------------------------
// supplier_returns / supplier_return_lines
// ---------------------------------------------------------------------

export type SupplierReturnRow = {
  id: string
  supplier_id: string
  status: SupplierReturnStatus
  reason: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}
export type SupplierReturnInsert = {
  id?: string
  supplier_id: string
  status?: SupplierReturnStatus
  reason?: string | null
  created_by?: string | null
  created_at?: string
  updated_at?: string
}
export type SupplierReturnUpdate = Partial<SupplierReturnInsert>

export type SupplierReturnLineRow = {
  id: string
  supplier_return_id: string
  stock_item_id: string
  quantity: number
  unit_cost: number | null
  created_at: string
}
export type SupplierReturnLineInsert = {
  id?: string
  supplier_return_id: string
  stock_item_id: string
  quantity: number
  unit_cost?: number | null
  created_at?: string
}
export type SupplierReturnLineUpdate = Partial<SupplierReturnLineInsert>

// ---------------------------------------------------------------------
// vehicle_models / vehicles / lubricants / fitments
// ---------------------------------------------------------------------

export type VehicleModelRow = {
  id: string
  make: string
  model: string
  generation: string | null
  year_from: number | null
  year_to: number | null
  engine_code: string | null
  fuel_type: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type VehicleModelInsert = {
  id?: string
  make: string
  model: string
  generation?: string | null
  year_from?: number | null
  year_to?: number | null
  engine_code?: string | null
  fuel_type?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type VehicleModelUpdate = Partial<VehicleModelInsert>

export type VehicleRow = {
  id: string
  registration: string | null
  vin: string | null
  vehicle_model_id: string | null
  colour: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type VehicleInsert = {
  id?: string
  registration?: string | null
  vin?: string | null
  vehicle_model_id?: string | null
  colour?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type VehicleUpdate = Partial<VehicleInsert>

export type VehicleModelLubricantRow = {
  id: string
  vehicle_model_id: string
  lubricant_type: string
  specification: string
  capacity_litres: number | null
  notes: string | null
}
export type VehicleModelLubricantInsert = {
  id?: string
  vehicle_model_id: string
  lubricant_type: string
  specification: string
  capacity_litres?: number | null
  notes?: string | null
}
export type VehicleModelLubricantUpdate = Partial<VehicleModelLubricantInsert>

export type VehicleModelFitmentRow = {
  id: string
  vehicle_model_id: string
  stock_item_id: string
  notes: string | null
}
export type VehicleModelFitmentInsert = {
  id?: string
  vehicle_model_id: string
  stock_item_id: string
  notes?: string | null
}
export type VehicleModelFitmentUpdate = Partial<VehicleModelFitmentInsert>

// ---------------------------------------------------------------------
// Views (read-only)
// ---------------------------------------------------------------------

export type ReorderReportRow = {
  id: string
  item_type: StockItemType
  id_number: string
  name: string
  supplier_id: string | null
  supplier_name: string | null
  quantity_on_hand: number
  ideal_stock_level: number
  quantity_to_order: number
}

export type PurchaseCostsWeeklyRow = {
  week_start: string
  supplier_id: string
  supplier_name: string
  total_cost: number
}

export type SupplierReturnCreditsWeeklyRow = {
  week_start: string
  supplier_id: string
  supplier_name: string
  total_credit: number
}

// ---------------------------------------------------------------------
// Database (Supabase client generic parameter)
// ---------------------------------------------------------------------

// Every table/view below carries `Relationships: []`. The Supabase client's
// generic constraints (GenericTable / GenericView in @supabase/postgrest-js)
// require that field to exist even though we're not modelling foreign-key
// relationship metadata by hand — omitting it silently breaks type
// inference on .insert()/.update() (everything degrades to `never`) rather
// than raising a clear error. The real `supabase gen types` output fills
// this in with actual FK metadata; ours just satisfies the shape.
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow
        Insert: ProfileInsert
        Update: ProfileUpdate
        Relationships: []
      }
      suppliers: {
        Row: SupplierRow
        Insert: SupplierInsert
        Update: SupplierUpdate
        Relationships: []
      }
      stock_items: {
        Row: StockItemRow
        Insert: StockItemInsert
        Update: StockItemUpdate
        Relationships: []
      }
      part_details: {
        Row: PartDetailsRow
        Insert: PartDetailsInsert
        Update: PartDetailsUpdate
        Relationships: []
      }
      tyre_details: {
        Row: TyreDetailsRow
        Insert: TyreDetailsInsert
        Update: TyreDetailsUpdate
        Relationships: []
      }
      stock_movements: {
        Row: StockMovementRow
        Insert: StockMovementInsert
        // No Update type: the ledger is append-only (no UPDATE RLS policy
        // in 0002_domain_schema.sql) — `never` makes `.update()` a
        // compile-time error here as a reminder, not just a runtime one.
        Update: never
        Relationships: []
      }
      purchase_orders: {
        Row: PurchaseOrderRow
        Insert: PurchaseOrderInsert
        Update: PurchaseOrderUpdate
        Relationships: []
      }
      purchase_order_lines: {
        Row: PurchaseOrderLineRow
        Insert: PurchaseOrderLineInsert
        Update: PurchaseOrderLineUpdate
        Relationships: []
      }
      supplier_returns: {
        Row: SupplierReturnRow
        Insert: SupplierReturnInsert
        Update: SupplierReturnUpdate
        Relationships: []
      }
      supplier_return_lines: {
        Row: SupplierReturnLineRow
        Insert: SupplierReturnLineInsert
        Update: SupplierReturnLineUpdate
        Relationships: []
      }
      vehicle_models: {
        Row: VehicleModelRow
        Insert: VehicleModelInsert
        Update: VehicleModelUpdate
        Relationships: []
      }
      vehicles: {
        Row: VehicleRow
        Insert: VehicleInsert
        Update: VehicleUpdate
        Relationships: []
      }
      vehicle_model_lubricants: {
        Row: VehicleModelLubricantRow
        Insert: VehicleModelLubricantInsert
        Update: VehicleModelLubricantUpdate
        Relationships: []
      }
      vehicle_model_fitments: {
        Row: VehicleModelFitmentRow
        Insert: VehicleModelFitmentInsert
        Update: VehicleModelFitmentUpdate
        Relationships: []
      }
    }
    Views: {
      v_reorder_report: { Row: ReorderReportRow; Relationships: [] }
      v_purchase_costs_weekly: { Row: PurchaseCostsWeeklyRow; Relationships: [] }
      v_supplier_return_credits_weekly: {
        Row: SupplierReturnCreditsWeeklyRow
        Relationships: []
      }
    }
    Functions: Record<string, never>
    Enums: {
      staff_role: StaffRole
      stock_item_type: StockItemType
      tyre_season: TyreSeason
      tyre_tier: TyreTier
      stock_movement_type: StockMovementType
      purchase_order_status: PurchaseOrderStatus
      supplier_return_status: SupplierReturnStatus
    }
  }
}
