/**
 * Hand-written types matching supabase/migrations/0001-0017.
 *
 * Once your Supabase project is linked, regenerate the real (guaranteed
 * accurate) types and replace this file entirely:
 *
 *   npx supabase gen types typescript --project-id <your-project-ref> > src/types/database.types.ts
 *
 * Until then, keep this file in sync by hand whenever a migration changes
 * the schema — the Supabase client is generic over this type, so a
 * mismatch won't fail the build, it'll just type-check against the wrong
 * shape.
 *
 * Each table below follows the shape the Supabase CLI generates: `Row` is
 * what a select returns, `Insert` is what you may pass to `.insert()`
 * (columns with a default or that are nullable are optional), `Update` is
 * everything optional (what `.update()` accepts). Columns generated by
 * Postgres (`tyre_details.size_label`) are omitted from Insert/Update —
 * the database rejects an explicit value for those.
 */

// 'staff' is a legacy fallback value — new accounts default to
// 'mechanic' as of migration 0004. Kept on the enum for compatibility;
// don't default new UI to it.
export type StaffRole = "admin" | "manager" | "mechanic" | "staff"
export type StockItemType = "part" | "tyre"
export type TyreSeason = "summer" | "winter" | "all_season"
export type TyreTier = "budget" | "mid_range" | "premium"
// Replaces the old is_xl/is_commercial booleans (0014_tyre_load_rating.sql,
// Sept 2026 "Load Rated" rename) — one tyre has exactly one load rating.
export type TyreLoadRating = "standard" | "xl" | "commercial"
export type StockMovementType =
  | "initial"
  | "goods_in"
  | "used"
  | "return_to_supplier"
  | "adjustment"
export type PurchaseOrderStatus =
  | "draft"
  | "ordered"
  | "partially_received"
  | "received"
  | "cancelled"
export type SupplierReturnStatus = "draft" | "sent" | "credited"
export type StockTakeStatus = "in_progress" | "completed" | "cancelled"
export type JobStatus = "open" | "closed"
export type ConsignmentLotStatus = "on_consignment" | "committed" | "returned"
// 0016_black_circle_stock.sql
export type BlackCircleLotStatus = "in_stock" | "used" | "returned"
// 0018_stock_lots_and_status.sql — the new generic Ordered/Owned/On
// Account/Returned status, tracked per received batch (see that
// migration's header for the full design). Distinct from
// ConsignmentLotStatus/BlackCircleLotStatus above, which keep their own
// separate lifecycles untouched.
export type StockLotStatus = "ordered" | "owned" | "on_account" | "returned"

// ---------------------------------------------------------------------
// profiles (0001_init.sql)
// ---------------------------------------------------------------------

export type ProfileRow = {
  id: string
  full_name: string
  role: StaffRole
  created_at: string
  updated_at: string
}
export type ProfileInsert = {
  id: string
  full_name: string
  role?: StaffRole
  created_at?: string
  updated_at?: string
}
export type ProfileUpdate = Partial<ProfileInsert>

// ---------------------------------------------------------------------
// suppliers
// ---------------------------------------------------------------------

export type SupplierRow = {
  id: string
  name: string
  contact_name: string | null
  phone: string | null
  email: string | null
  // 0015_supplier_address_and_on_account_fields.sql
  address: string | null
  notes: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}
export type SupplierInsert = {
  id?: string
  name: string
  contact_name?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  notes?: string | null
  is_active?: boolean
  created_at?: string
  updated_at?: string
}
export type SupplierUpdate = Partial<SupplierInsert>

// ---------------------------------------------------------------------
// stock_items
// ---------------------------------------------------------------------

export type StockItemRow = {
  id: string
  item_type: StockItemType
  // Also what's scanned as a barcode — "ID & Barcode are the same
  // thing" (Joanne). Migration 0005 dropped the separate `barcode`
  // column; this is the single field for both.
  id_number: string
  name: string
  supplier_id: string | null
  cost_price: number
  selling_price: number
  is_non_returnable: boolean
  is_consignment: boolean
  // 0016_black_circle_stock.sql — see that migration's header for why
  // this is a flag on the product rather than keyed off the supplier's
  // name. Independent of is_consignment: a product is either a normal
  // owned item, an on-account item, or a Black Circle item (the Add
  // Product form and stock/new/actions.ts don't currently stop someone
  // ticking both is_consignment and is_black_circle at once, since
  // nothing in scope asked for that cross-validation — treat that combo
  // as unsupported/undefined rather than relied on).
  is_black_circle: boolean
  vehicle_note: string | null
  quantity_on_hand: number
  ideal_stock_level: number
  location: string | null
  notes: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}
export type StockItemInsert = {
  id?: string
  item_type: StockItemType
  id_number: string
  name: string
  supplier_id?: string | null
  cost_price?: number
  selling_price?: number
  is_non_returnable?: boolean
  is_consignment?: boolean
  is_black_circle?: boolean
  vehicle_note?: string | null
  quantity_on_hand?: number
  ideal_stock_level?: number
  location?: string | null
  notes?: string | null
  is_active?: boolean
  created_at?: string
  updated_at?: string
}
export type StockItemUpdate = Partial<StockItemInsert>

// ---------------------------------------------------------------------
// part_details
// ---------------------------------------------------------------------

export type PartDetailsRow = {
  stock_item_id: string
  vehicle_make: string | null
  vehicle_model: string | null
  manufacturer_part_number: string | null
  oem_part_number: string | null
}
export type PartDetailsInsert = {
  stock_item_id: string
  vehicle_make?: string | null
  vehicle_model?: string | null
  manufacturer_part_number?: string | null
  oem_part_number?: string | null
}
export type PartDetailsUpdate = Partial<PartDetailsInsert>

// ---------------------------------------------------------------------
// tyre_details
// ---------------------------------------------------------------------

export type TyreDetailsRow = {
  stock_item_id: string
  width: number
  profile: number
  rim_diameter: number
  size_label: string // generated column — read-only
  load_index: string | null
  speed_rating: string | null
  load_rating: TyreLoadRating
  season: TyreSeason
  tier: TyreTier
  brand: string | null
  pattern: string | null
}
export type TyreDetailsInsert = {
  stock_item_id: string
  width: number
  profile: number
  rim_diameter: number
  load_index?: string | null
  speed_rating?: string | null
  load_rating?: TyreLoadRating
  season?: TyreSeason
  tier?: TyreTier
  brand?: string | null
  pattern?: string | null
}
export type TyreDetailsUpdate = Partial<TyreDetailsInsert>

// ---------------------------------------------------------------------
// stock_movements (append-only ledger)
// ---------------------------------------------------------------------

export type StockMovementRow = {
  id: string
  stock_item_id: string
  movement_type: StockMovementType
  quantity: number
  // Legacy free-text field, pre-0009 — left null on new 'used' rows,
  // which now go through job_id instead. Still populated on old rows.
  job_number: string | null
  // Set on 'used' movements recorded from a job (0009_jobs.sql). RLS
  // requires this to reference a still-open job for new inserts — see
  // that migration's "Staff can record stock usage" policy.
  job_id: string | null
  purchase_order_id: string | null
  supplier_return_id: string | null
  // Set on 'adjustment' movements written by stock take reconciliation
  // (0007_stock_take_reconciliation.sql) — traces the movement back to
  // the stock take that produced it, same idea as purchase_order_id /
  // supplier_return_id above.
  stock_take_id: string | null
  // Set on the 'goods_in' movement that receives a consignment lot, and
  // on the 'return_to_supplier' movement that sends one back unused
  // (0011_consignment_stock_lots.sql) — same "trace back to origin"
  // idea as job_id/purchase_order_id/stock_take_id above.
  consignment_lot_id: string | null
  // Set on goods_in/used/return_to_supplier movements for Black Circle
  // stock (0016_black_circle_stock.sql) — same "trace back to origin"
  // idea as consignment_lot_id above.
  black_circle_lot_id: string | null
  // Set on the 'goods_in' movement created by the new Receive Stock /
  // Add Product flows for a stock_lots row with status 'owned'
  // (0018_stock_lots_and_status.sql) — an 'ordered' lot never gets a
  // movement, so this stays null until the lot is actually received.
  stock_lot_id: string | null
  performed_by: string | null
  notes: string | null
  created_at: string
}
export type StockMovementInsert = {
  id?: string
  stock_item_id: string
  movement_type: StockMovementType
  quantity: number
  job_number?: string | null
  job_id?: string | null
  purchase_order_id?: string | null
  supplier_return_id?: string | null
  stock_take_id?: string | null
  consignment_lot_id?: string | null
  black_circle_lot_id?: string | null
  stock_lot_id?: string | null
  performed_by?: string | null
  notes?: string | null
  created_at?: string
}
// No update type exported: the ledger is append-only (see RLS policy in
// 0002_domain_schema.sql) — there is intentionally no UPDATE policy.

// ---------------------------------------------------------------------
// consignment_stock_lots (0011_consignment_stock_lots.sql)
// ---------------------------------------------------------------------
// Consignment-only lot tracking — owned stock keeps using stock_items.
// quantity_on_hand/cost_price exactly as before. See that migration's
// header comment for the full design (why lot-tracking is scoped to
// consignment, what "committed" means, why payment_due_date is stored
// rather than computed). paid_at/paid_by added in 0012_consignment_lot_
// payment.sql — a "pending payments" report needs a way for something
// to leave "pending" once it's actually been paid.

export type ConsignmentStockLotRow = {
  id: string
  stock_item_id: string
  quantity: number
  // "Price exc. VAT" in the UI (0015 — see that migration's header
  // comment for why this didn't get a second, separate column).
  cost_price: number
  received_at: string
  received_by: string | null
  due_back_at: string
  status: ConsignmentLotStatus
  committed_at: string | null
  committed_by: string | null
  payment_due_date: string | null
  paid_at: string | null
  paid_by: string | null
  returned_at: string | null
  returned_by: string | null
  // 0015_supplier_address_and_on_account_fields.sql — captured at receipt,
  // per item (not grouped under a separate invoice entity — see
  // on-account/receive/actions.ts).
  invoice_number: string | null
  vehicle_registration: string | null
  price_inc_vat: number | null
  notes: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}
export type ConsignmentStockLotInsert = {
  id?: string
  stock_item_id: string
  quantity: number
  cost_price?: number
  received_at?: string
  received_by?: string | null
  due_back_at: string
  status?: ConsignmentLotStatus
  committed_at?: string | null
  committed_by?: string | null
  payment_due_date?: string | null
  paid_at?: string | null
  paid_by?: string | null
  returned_at?: string | null
  returned_by?: string | null
  invoice_number?: string | null
  vehicle_registration?: string | null
  price_inc_vat?: number | null
  notes?: string | null
  created_by?: string | null
  created_at?: string
  updated_at?: string
}
export type ConsignmentStockLotUpdate = Partial<ConsignmentStockLotInsert>

// ---------------------------------------------------------------------
// black_circle_stock_lots (0016_black_circle_stock.sql)
// ---------------------------------------------------------------------
// Black Circles-style job-locked stock — see that migration's header
// comment for the full design. Mirrors consignment_stock_lots' shape,
// with job_id fixed and required instead of consignment's due_back_at/
// payment fields, since this stock is never owned or paid for.

export type BlackCircleStockLotRow = {
  id: string
  stock_item_id: string
  job_id: string
  quantity: number
  received_at: string
  received_by: string | null
  status: BlackCircleLotStatus
  used_at: string | null
  used_by: string | null
  returned_at: string | null
  returned_by: string | null
  notes: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}
export type BlackCircleStockLotInsert = {
  id?: string
  stock_item_id: string
  job_id: string
  quantity: number
  received_at?: string
  received_by?: string | null
  status?: BlackCircleLotStatus
  used_at?: string | null
  used_by?: string | null
  returned_at?: string | null
  returned_by?: string | null
  notes?: string | null
  created_by?: string | null
  created_at?: string
  updated_at?: string
}
export type BlackCircleStockLotUpdate = Partial<BlackCircleStockLotInsert>

// ---------------------------------------------------------------------
// stock_lots (0018_stock_lots_and_status.sql)
// ---------------------------------------------------------------------
// The new generic Ordered/Owned/On Account/Returned batch tracking used
// by the redesigned Stock hub (Add Order, Receive Stock, Return Stock) —
// see that migration's header for the full design. consignment_stock_lots
// and black_circle_stock_lots keep their own separate lifecycle and
// screens, untouched by this table.

export type StockLotRow = {
  id: string
  stock_item_id: string
  quantity: number
  cost_price: number
  price_inc_vat: number | null
  status: StockLotStatus
  ordered_at: string | null
  received_at: string
  received_by: string | null
  notes: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}
export type StockLotInsert = {
  id?: string
  stock_item_id: string
  quantity: number
  cost_price?: number
  price_inc_vat?: number | null
  status?: StockLotStatus
  ordered_at?: string | null
  received_at?: string
  received_by?: string | null
  notes?: string | null
  created_by?: string | null
  created_at?: string
  updated_at?: string
}
export type StockLotUpdate = Partial<StockLotInsert>

// ---------------------------------------------------------------------
// purchase_orders / purchase_order_lines
// ---------------------------------------------------------------------

export type PurchaseOrderRow = {
  id: string
  supplier_id: string
  status: PurchaseOrderStatus
  ordered_at: string | null
  expected_at: string | null
  created_by: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type PurchaseOrderInsert = {
  id?: string
  supplier_id: string
  status?: PurchaseOrderStatus
  ordered_at?: string | null
  expected_at?: string | null
  created_by?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type PurchaseOrderUpdate = Partial<PurchaseOrderInsert>

export type PurchaseOrderLineRow = {
  id: string
  purchase_order_id: string
  stock_item_id: string
  quantity_ordered: number
  quantity_received: number
  unit_cost: number
  created_at: string
  updated_at: string
}
export type PurchaseOrderLineInsert = {
  id?: string
  purchase_order_id: string
  stock_item_id: string
  quantity_ordered: number
  quantity_received?: number
  unit_cost: number
  created_at?: string
  updated_at?: string
}
export type PurchaseOrderLineUpdate = Partial<PurchaseOrderLineInsert>

// ---------------------------------------------------------------------
// supplier_returns / supplier_return_lines
// ---------------------------------------------------------------------

export type SupplierReturnRow = {
  id: string
  supplier_id: string
  status: SupplierReturnStatus
  reason: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}
export type SupplierReturnInsert = {
  id?: string
  supplier_id: string
  status?: SupplierReturnStatus
  reason?: string | null
  created_by?: string | null
  created_at?: string
  updated_at?: string
}
export type SupplierReturnUpdate = Partial<SupplierReturnInsert>

export type SupplierReturnLineRow = {
  id: string
  supplier_return_id: string
  stock_item_id: string
  quantity: number
  unit_cost: number | null
  created_at: string
}
export type SupplierReturnLineInsert = {
  id?: string
  supplier_return_id: string
  stock_item_id: string
  quantity: number
  unit_cost?: number | null
  created_at?: string
}
export type SupplierReturnLineUpdate = Partial<SupplierReturnLineInsert>

// ---------------------------------------------------------------------
// stock_takes / stock_take_counts (0006_stock_takes.sql)
// ---------------------------------------------------------------------

export type StockTakeRow = {
  id: string
  status: StockTakeStatus
  started_by: string | null
  started_at: string
  completed_by: string | null
  completed_at: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type StockTakeInsert = {
  id?: string
  status?: StockTakeStatus
  started_by?: string | null
  started_at?: string
  completed_by?: string | null
  completed_at?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type StockTakeUpdate = Partial<StockTakeInsert>

export type StockTakeCountRow = {
  id: string
  stock_take_id: string
  stock_item_id: string
  counted_quantity: number
  expected_quantity: number
  counted_by: string | null
  counted_at: string
  notes: string | null
  // Set once this discrepancy has been applied to actual stock levels
  // (0007_stock_take_reconciliation.sql) — admin/manager only, see the
  // trigger guard in that migration. reconciled_movement_id points at
  // the stock_movements row it wrote, or stays null if the count matched
  // (no adjustment needed, but still marked reconciled/reviewed).
  reconciled_at: string | null
  reconciled_movement_id: string | null
}
export type StockTakeCountInsert = {
  id?: string
  stock_take_id: string
  stock_item_id: string
  counted_quantity: number
  expected_quantity: number
  counted_by?: string | null
  counted_at?: string
  notes?: string | null
  reconciled_at?: string | null
  reconciled_movement_id?: string | null
}
export type StockTakeCountUpdate = Partial<StockTakeCountInsert>

// ---------------------------------------------------------------------
// vehicle_models / vehicles / lubricants / fitments
// ---------------------------------------------------------------------

export type VehicleModelRow = {
  id: string
  make: string
  model: string
  generation: string | null
  year_from: number | null
  year_to: number | null
  engine_code: string | null
  fuel_type: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type VehicleModelInsert = {
  id?: string
  make: string
  model: string
  generation?: string | null
  year_from?: number | null
  year_to?: number | null
  engine_code?: string | null
  fuel_type?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type VehicleModelUpdate = Partial<VehicleModelInsert>

export type VehicleRow = {
  id: string
  registration: string | null
  vin: string | null
  vehicle_model_id: string | null
  colour: string | null
  notes: string | null
  created_at: string
  updated_at: string
}
export type VehicleInsert = {
  id?: string
  registration?: string | null
  vin?: string | null
  vehicle_model_id?: string | null
  colour?: string | null
  notes?: string | null
  created_at?: string
  updated_at?: string
}
export type VehicleUpdate = Partial<VehicleInsert>

export type VehicleModelLubricantRow = {
  id: string
  vehicle_model_id: string
  lubricant_type: string
  specification: string
  capacity_litres: number | null
  notes: string | null
}
export type VehicleModelLubricantInsert = {
  id?: string
  vehicle_model_id: string
  lubricant_type: string
  specification: string
  capacity_litres?: number | null
  notes?: string | null
}
export type VehicleModelLubricantUpdate = Partial<VehicleModelLubricantInsert>

export type VehicleModelFitmentRow = {
  id: string
  vehicle_model_id: string
  stock_item_id: string
  notes: string | null
}
export type VehicleModelFitmentInsert = {
  id?: string
  vehicle_model_id: string
  stock_item_id: string
  notes?: string | null
}
export type VehicleModelFitmentUpdate = Partial<VehicleModelFitmentInsert>

// ---------------------------------------------------------------------
// jobs (0009_jobs.sql, extended by 0010_jobs_enhancements.sql)
// ---------------------------------------------------------------------

export type JobRow = {
  id: string
  job_number: string
  vehicle_registration: string | null
  vehicle_id: string | null
  notes: string | null
  status: JobStatus
  created_by: string | null
  created_at: string
  closed_by: string | null
  closed_at: string | null
  updated_at: string
  // 0010_jobs_enhancements.sql — customer contact details and the date
  // the work itself is for/on (distinct from created_at, the system
  // "opened" timestamp).
  customer_name: string | null
  customer_company: string | null
  customer_email: string | null
  job_date: string | null
  // Tracks the most recent reopen only (same "latest event" shape as
  // closed_by/closed_at above) — reopening is admin-only, enforced by the
  // guard_job_reopen trigger, not by RLS alone (see that migration).
  reopened_by: string | null
  reopened_at: string | null
}
export type JobInsert = {
  id?: string
  job_number: string
  vehicle_registration?: string | null
  vehicle_id?: string | null
  notes?: string | null
  status?: JobStatus
  created_by?: string | null
  created_at?: string
  closed_by?: string | null
  closed_at?: string | null
  updated_at?: string
  customer_name?: string | null
  customer_company?: string | null
  customer_email?: string | null
  job_date?: string | null
  reopened_by?: string | null
  reopened_at?: string | null
}
export type JobUpdate = Partial<JobInsert>

// ---------------------------------------------------------------------
// Views (read-only)
// ---------------------------------------------------------------------

export type ReorderReportRow = {
  id: string
  item_type: StockItemType
  id_number: string
  name: string
  supplier_id: string | null
  supplier_name: string | null
  quantity_on_hand: number
  ideal_stock_level: number
  quantity_to_order: number
}

export type PurchaseCostsWeeklyRow = {
  week_start: string
  supplier_id: string
  supplier_name: string
  total_cost: number
}

export type SupplierReturnCreditsWeeklyRow = {
  week_start: string
  supplier_id: string
  supplier_name: string
  total_credit: number
}

// v_consignment_pending_payments (0013_consignment_pending_payments_view.sql)
// — committed-but-unpaid consignment lots only; see that migration for why
// on_consignment and paid lots are excluded.
export type ConsignmentPendingPaymentRow = {
  lot_id: string
  stock_item_id: string
  id_number: string
  name: string
  supplier_id: string | null
  supplier_name: string | null
  quantity: number
  cost_price: number
  amount_due: number
  received_at: string
  committed_at: string | null
  payment_due_date: string | null
  is_overdue: boolean
  // 0015_supplier_address_and_on_account_fields.sql — added to the view
  // alongside the new columns on consignment_stock_lots (see
  // 0017_on_account_view_new_fields.sql).
  invoice_number: string | null
  vehicle_registration: string | null
  price_inc_vat: number | null
}

// ---------------------------------------------------------------------
// Database (Supabase client generic parameter)
// ---------------------------------------------------------------------

// Every table/view below carries `Relationships: []`. The Supabase client's
// generic constraints (GenericTable / GenericView in @supabase/postgrest-js)
// require that field to exist even though we're not modelling foreign-key
// relationship metadata by hand — omitting it silently breaks type
// inference on .insert()/.update() (everything degrades to `never`) rather
// than raising a clear error. The real `supabase gen types` output fills
// this in with actual FK metadata; ours just satisfies the shape.
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow
        Insert: ProfileInsert
        Update: ProfileUpdate
        Relationships: []
      }
      suppliers: {
        Row: SupplierRow
        Insert: SupplierInsert
        Update: SupplierUpdate
        Relationships: []
      }
      stock_items: {
        Row: StockItemRow
        Insert: StockItemInsert
        Update: StockItemUpdate
        Relationships: []
      }
      part_details: {
        Row: PartDetailsRow
        Insert: PartDetailsInsert
        Update: PartDetailsUpdate
        Relationships: []
      }
      tyre_details: {
        Row: TyreDetailsRow
        Insert: TyreDetailsInsert
        Update: TyreDetailsUpdate
        Relationships: []
      }
      stock_movements: {
        Row: StockMovementRow
        Insert: StockMovementInsert
        // No Update type: the ledger is append-only (no UPDATE RLS policy
        // in 0002_domain_schema.sql) — `never` makes `.update()` a
        // compile-time error here as a reminder, not just a runtime one.
        Update: never
        Relationships: []
      }
      consignment_stock_lots: {
        Row: ConsignmentStockLotRow
        Insert: ConsignmentStockLotInsert
        Update: ConsignmentStockLotUpdate
        Relationships: []
      }
      black_circle_stock_lots: {
        Row: BlackCircleStockLotRow
        Insert: BlackCircleStockLotInsert
        Update: BlackCircleStockLotUpdate
        Relationships: []
      }
      stock_lots: {
        Row: StockLotRow
        Insert: StockLotInsert
        Update: StockLotUpdate
        Relationships: []
      }
      purchase_orders: {
        Row: PurchaseOrderRow
        Insert: PurchaseOrderInsert
        Update: PurchaseOrderUpdate
        Relationships: []
      }
      purchase_order_lines: {
        Row: PurchaseOrderLineRow
        Insert: PurchaseOrderLineInsert
        Update: PurchaseOrderLineUpdate
        Relationships: []
      }
      supplier_returns: {
        Row: SupplierReturnRow
        Insert: SupplierReturnInsert
        Update: SupplierReturnUpdate
        Relationships: []
      }
      supplier_return_lines: {
        Row: SupplierReturnLineRow
        Insert: SupplierReturnLineInsert
        Update: SupplierReturnLineUpdate
        Relationships: []
      }
      stock_takes: {
        Row: StockTakeRow
        Insert: StockTakeInsert
        Update: StockTakeUpdate
        Relationships: []
      }
      stock_take_counts: {
        Row: StockTakeCountRow
        Insert: StockTakeCountInsert
        Update: StockTakeCountUpdate
        Relationships: []
      }
      vehicle_models: {
        Row: VehicleModelRow
        Insert: VehicleModelInsert
        Update: VehicleModelUpdate
        Relationships: []
      }
      vehicles: {
        Row: VehicleRow
        Insert: VehicleInsert
        Update: VehicleUpdate
        Relationships: []
      }
      vehicle_model_lubricants: {
        Row: VehicleModelLubricantRow
        Insert: VehicleModelLubricantInsert
        Update: VehicleModelLubricantUpdate
        Relationships: []
      }
      vehicle_model_fitments: {
        Row: VehicleModelFitmentRow
        Insert: VehicleModelFitmentInsert
        Update: VehicleModelFitmentUpdate
        Relationships: []
      }
      jobs: {
        Row: JobRow
        Insert: JobInsert
        Update: JobUpdate
        Relationships: []
      }
    }
    Views: {
      v_reorder_report: { Row: ReorderReportRow; Relationships: [] }
      v_purchase_costs_weekly: { Row: PurchaseCostsWeeklyRow; Relationships: [] }
      v_supplier_return_credits_weekly: {
        Row: SupplierReturnCreditsWeeklyRow
        Relationships: []
      }
      v_consignment_pending_payments: {
        Row: ConsignmentPendingPaymentRow
        Relationships: []
      }
    }
    Functions: Record<string, never>
    Enums: {
      staff_role: StaffRole
      stock_item_type: StockItemType
      tyre_season: TyreSeason
      tyre_tier: TyreTier
      tyre_load_rating: TyreLoadRating
      stock_movement_type: StockMovementType
      purchase_order_status: PurchaseOrderStatus
      supplier_return_status: SupplierReturnStatus
      stock_take_status: StockTakeStatus
      job_status: JobStatus
      consignment_lot_status: ConsignmentLotStatus
      black_circle_lot_status: BlackCircleLotStatus
      stock_lot_status: StockLotStatus
    }
  }
}
